version: '3.7'

services:
  frontend:
    image: mern-frontend:latest
    container_name: mern-frontend
    build:
      context: ./frontend
      args:
        NODE_ENV: production
    environment:
      CUSTOMER_DOMAIN: mern-customer.justinmanche.com
      ADMIN_DOMAIN: mern-admin.justinmanche.com
      API_HOST: backend
      API_PORT: 4000
    ports:
      - 443:443
    depends_on:
      - backend
    volumes:
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - /etc/ssl/key.pem:/etc/ssl/key.pem
      - /etc/ssl/cloudflare.crt:/etc/ssl/cloudflare.crt

  backend:
    image: mern-backend:latest
    container_name: mern-backend
    build: .
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_DB: mern
      PORT: 4000
      SESSION_SECRET: mern
      NODE_ENV: production
      ADMIN_DOMAIN: http://mern-admin.justinmanche.com
      CUSTOMER_DOMAIN: http://mern-customer.justinmanche.com
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mern-db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
