version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: production
    environment:
      CUSTOMER_DOMAIN: mern-customer.com
      ADMIN_DOMAIN: mern-admin.com
      API_HOST: backend
      API_PORT: 4000
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build: .
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_DB: mern
      PORT: 4000
      SESSION_SECRET: mern
      NODE_ENV: production
      ADMIN_DOMAIN: http://mern-admin.com
      CUSTOMER_DOMAIN: http://mern-customer.com
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
