name: Build
on:
  workflow_run:
    workflows: [Test]
    types:
      - completed
      - requested

jobs:
  build:
    name: "Build"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build backend
        run: |
          cd $GITHUB_WORKSPACE
          docker build . -t backend
      - name: Build frontend
        run: |
          cd $GITHUB_WORKSPACE/frontend
          docker build . -t frontend
