name: Deploy
on:
  workflow_run:
    workflows: [Build]
    branches: [master, ci]
    types: [completed]

jobs:
  deploy:
    name: "Deploy"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check out the source
        run: ssh production 'cd ~/mern && git fetch && git reset --hard origin/master'

      - name: Deploy
        run: ssh production 'cd ~/mern && docker stack deploy --compose-file docker-compose.yml mern'
