name: Deploy
on:
  workflow_run:
    workflows: [Build]
    branches: [master, ci]
    types: [completed]

jobs:
  deploy:
    name: "Deploy"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get latest image
        run: echo "Hey there"
